name = "Yupilandia-Forge"
author = "ScatherM02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d87c43d85ef2fa09be85bc60098760d1955f3f9a2e45a0f8d4b800043e398a8b"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
