name = "Yupilandia-Forge"
author = "ScatherM02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f231ddafd13e4872b8871a957679b00730a8f3c6d804d934f5a4831585beceba"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
