name = "Yupilandia-Forge"
author = "ScatherM02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0766f1a91ade258def189c47c46e6b0fe893591e8bcebf37fd3d2c8a46fa1808"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
